project:
  type: website
  output-dir: docs

website:
  search: 
    location: navbar
    type: overlay
  navbar:
    logo: img/home.jpg
    logo-href: index.qmd
    left:
      - about.qmd
      - text: "cv"
        href: cv.qmd

format:
  html:
    theme:
      light: yeti
    css: styles.css
    toc: true
    page-layout: full

editor: visual

